### ISSUE TITLE
Support query/mutation in endpoint

### ISSUE THREAD

**Issue by liweihan** [jycouet/kitql#174]
**Is your feature request related to a problem? Please describe.**

This might be more like an issue for houdini, but as an KitQL user, it seems that since 0.7 we lost the ability to query(as a graphql client) inside a sveltekit endpoint? 

**Describe alternatives you've considered**

I tried to re-construct the LoadEvent from RequestEvent (sort of) but looks like houdini still need to access the window object:

```
export async function post(event: RequestEvent) {
	await GQL_GetPriceForCheckout.fetch({
		event: { fetch, session: event.locals, params: event.params },
		variables: { priceID }
	});
}
```
error when trying to access the endpoint:
```

window is not defined
ReferenceError: window is not defined
    at Module.executeQuery (/$houdini/runtime/lib/network.js:95:16)
    at Object.mutate (/$houdini/runtime/stores/mutation.js:65:37)
    at post (/Users/weihan/src/MozartWeb/src/routes/prices/checkout/stripe-session.ts:42:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async render_endpoint (file:///Users/weihan/src/MozartWeb/.svelte-kit/runtime/server/index.js:269:19)
    at async resolve (file:///Users/weihan/src/MozartWeb/.svelte-kit/runtime/server/index.js:3345:11)
    at async Object.handle (/Users/weihan/src/MozartWeb/src/hooks/index.ts:33:18)
    at async respond (file:///Users/weihan/src/MozartWeb/.svelte-kit/runtime/server/index.js:3290:20)
    at async file:///Users/weihan/src/MozartWeb/node_modules/@sveltejs/kit/dist/vite.js:2322:22

```

**Comment by jycouet** [comment]
Hi, 

You were doing this in `KitQL`? (I didn't have this in mind ^^)
Can you tell me a bit more about this use case?

Why don't you put `GQL_GetPriceForCheckout` in the `load` function?

**Comment by liweihan** [comment]
Hi @jycouet , because load is running on both the client and server, but for this case it is a check out process that I need to access data that requires a server side secret key, I use supabase & its graphql endpoint as my backend. So I need to query from my server side, as a client of supabase graphql endpoint, to fetch data that is only visible on the server side.

**Comment by jycouet** [comment]
Thank you for the extra info 👍
We will publish the new version soon.
