### ISSUE TITLE
vite-plugin-kit-routes Error on server start

### ISSUE THREAD

**Issue by ivshil** [jycouet/kitql#604]
### Describe the bug

-  $lib/ROUTES.ts is not generated on vite.config.ts (update with import and  added plugin "kitRoutes")
- error when starting dev server:

```
SyntaxError: Unexpected token, expected "," (14:4)
    at constructor (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:356:19)
    at TypeScriptParserMixin.raise (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:3223:19)
    at TypeScriptParserMixin.unexpected (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:3253:16)
    at TypeScriptParserMixin.expect (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:3585:28)
    at TypeScriptParserMixin.parseObjectLike (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:11650:14)
    at TypeScriptParserMixin.parseExprAtom (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:11155:23)
    at TypeScriptParserMixin.parseExprSubscripts (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:10857:23)
    at TypeScriptParserMixin.parseUpdate (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:10840:21)
    at TypeScriptParserMixin.parseMaybeUnary (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:10816:23)
    at TypeScriptParserMixin.parseMaybeUnary (/full/path/to/project/node_modules/.pnpm/@babel+parser@7.23.6/node_modules/@babel/parser/lib/index.js:9696:18)
 ELIFECYCLE  Command failed with exit code 1.
```

### Severity

blocking all usage of Houdini

### Steps to Reproduce the Bug

1. installing the plugin:

```
❯ pnpm add vite-plugin-kit-routes -D
Packages: +19
+++++++++++++++++++
Progress: resolved 517, reused 494, downloaded 0, added 0, done

devDependencies:
+ vite-plugin-kit-routes 0.5.1

Done in 4.2s
```

2. saving changes to vite.config.ts
```
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';
import { imagetools } from 'vite-imagetools';
import { kitRoutes } from 'vite-plugin-kit-routes'

const config: UserConfig = {
  plugins: [sveltekit(), imagetools(), kitRoutes()]
};

export default config;
```

**Comment by jycouet** [comment]
I'm not able to reproduce, could you do a repro somewhere?

**Comment by jycouet** [comment]
Any update?

**Comment by jycouet** [comment]
Feel free to re open if you have any update
